### ISSUE TITLE
src/Context.h has conflict with Tint build

### ISSUE THREAD

**Issue by gyagp** [webatintel/aquarium#198]
If we have src/Context.h, the build of Tint will fail as below:
In file included from ../../third_party/dawn/src/dawn_native/ShaderModule.cpp:30:
In file included from ../../third_party/dawn/third_party/tint/include\tint/tint.h:21:
In file included from ../..\src/context.h:15:
../..\src/Aquarium.h(155,22): warning: missing field 'blend' initializer [-Wmissing-field-initializers]
     MODELGROUP::FISH},

When building Tint, it relies on its own src/context.h. Thus if we also have src/Context.h (case insensitive on Windows) in Aquarium src/ folder, the Tint build will use this file instead of its own.

**Comment by hujiajie** [comment]
The root directory of Aquarium is added to the search path due to [this config](https://chromium.googlesource.com/chromium/src/build/+/52ccb296104e3a48444450f1007e67e5fb1c8038/config/compiler/BUILD.gn#236). The config is enabled by default (!), unless it's explicitly suppressed in Dawn/Tint/... like [this](https://chromium.googlesource.com/angle/angle/+/2e84e59ab3e38ddbc230a35ca31a2d6a63f7b5ee/gni/angle.gni#224).

**Comment by gyagp** [comment]
Thanks for the root cause. After sync, we plan to work around with different folder name. Close this issue.
